config/routes.rb
SportsOverload::Application.routes.draw do

  root :to => 'questions#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:show, :create, :new]

  resources :votes, :only => [:update]

  resources :questions, only: [:index, :show, :create, :new] do
    resources :answers, only: [:create, :new]

  end

  # resources :comments

    resources :questions do
      resources :comments, only: [:create, :new]
    end

    resources :answers do
      resources :comments, only: [:create, :new]
    end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
  attr_accessible :body
  belongs_to :question
  belongs_to :user
  validates_presence_of :body

  def vote_count
    up_votes = self.votes.select {|vote| vote.vote_type == true}
    down_votes = self.votes.select {|vote| vote.vote_type == false}
    up_votes.length - down_votes.length
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates_presence_of :body
  attr_accessible :body

  def most_recent_comments_first(question)
    question.comments.order('created_at asc')
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
    has_many :comments, as: :commentable
    has_many :votes, as: :voteable
    validates_presence_of :title, :user, :body
    attr_accessible :title, :body
    belongs_to :user
    has_many :answers

  def vote_count
    up_votes = self.votes.select {|vote| vote.vote_type == true}
    down_votes = self.votes.select {|vote| vote.vote_type == false}
    up_votes.length - down_votes.length
  end

  def order_answers_by_latest
    self.answers.order('created_at desc')
  end

  def self.questions_with_most_votes
    questions = Question.all
    question_votes = {}
    questions.each do |question|
        question_votes[question] = [question.votes.count]
    end
    question_votes = question_votes.sort_by {|k,v| v }.reverse
  end

  def self.question_with_recent_votes
    votes = Vote.all
    questions = {}
    votes.each do |vote|
      if vote.voteable_type == 'Question'
        questions[vote.voteable] = vote.created_at
      end
    end
    questions.sort_by{|k,v| v }.reverse
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_secure_password
  attr_accessible :username, :email, :password, :password_confirmation
  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :vote_type, :voteable_id, :voteable_type
  belongs_to :voteable, polymorphic: true

  def self.assign_vote_attributes(vote, params)
    vote.update_attributes(
        vote_type: params[:vote_type],
        voteable_id: params[:voteable]["id"],
        voteable_type: params[:voteable]["type"]
        )
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @answer = Answer.new
  end

  def create
    @question = Question.find params[:question_id]
    @answer = @question.answers.new params[:answer]
    @answer.user_id = session[:user_id]
    if @answer.save
      render partial:'/shared/answers', locals: {answer: @answer}
    else
      @errors = 'Answer cannot be blank'
      render partial: '/shared/errors', locals: {errors: @errors}, :status => :unprocessable_entity
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper AuthenticateHelper
  def current_user
    if session[:user_id]
      return User.find(session[:user_id])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    if params[:answer_id] == nil
      @question = Question.find(params[:question_id])
      create_comment_for('Question')
      @comment.commentable_id = @question.id
      render_comment_or_error
    else
      @answer = Answer.find(params[:answer_id])
      create_comment_for('Answer')
      @comment.commentable_id = @answer.id
      render_comment_or_error
    end
  end

  private

  def create_comment_for(type)
    @comment = Comment.new(params[:comment])
    @comment.commentable_type = type
    @comment.user_id = session[:user_id]
  end

  def render_comment_or_error
    if @comment.save
      render partial:'/shared/comments', locals: {comment: @comment}
    else
      @errors = 'Comment cannot be blank'
      render partial: '/shared/errors', locals: {errors: @errors}, :status => :unprocessable_entity
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order('created_at desc')
    @votes = Question.questions_with_most_votes
    @trending = Question.question_with_recent_votes
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new params[:question]
    @question.user_id = session[:user_id]
    if @question.save
      redirect_to question_path(@question)
    else
      render :nothing => true
    end
  end

  def show
    @comment = Comment.new
    @answer = Answer.new
    @question = Question.find params[:id]
    @answers = @question.order_answers_by_latest
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user_object = current_user
    if user_object && user_object.id == session[:user_id]
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    if @user.save!
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render new_user_path
    end
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def update
    vote = Vote.create
    if vote && params[:vote_type] == true
      p params
      Vote.assign_vote_attributes(vote, params)
      constant = params[:voteable]["type"].classify.constantize
      @voteable = constant.find(params[:voteable]["id"])
      render partial:'/shared/vote_count', locals: { voteable: @voteable }
    else
      Vote.assign_vote_attributes(vote, params)
      constant = params[:voteable]["type"].classify.constantize
      @voteable = constant.find(params[:voteable]["id"])
      render partial:'/shared/vote_count', locals: { voteable: @voteable }
    end
  end
end

app/helpers/application_helper.rb
require 'active_support/core_ext'

module ApplicationHelper

  def datetime_to_date(datetime)
    datetime.to_date
  end

  def pluralize_without_count(count, noun, text = nil)
    if count != 0
      count == 1 ? "#{noun}#{text}" : "#{noun.pluralize}#{text}"
    end
  end
end

module AuthenticateHelper
  def current_user
    if session[:user_id]
      return User.find(session[:user_id])
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">




  <title>SportsOverload</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= render 'shared/header' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/index.html.erb
<ul >
  <ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#recent" data-toggle="tab">Most Recent</a></li>
  <li><a href="#votes" data-toggle="tab">Highest Votes</a></li>
  <li><a href="#trending" data-toggle="tab">Trending</a></li>
</ul>
  <%= render '/shared/recent' %>

  <%= render '/shared/votes' %>
  <%= render '/shared/trending' %>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control'%>
    <%= f.label :body %>
    <%= f.text_area :body, :class => 'form-control' %>
    <%= f.button %>
  </div>
<% end %>

app/views/questions/show.html.erb
<div class='question col-md-12'>
  <div class="question-title">
    <h3 class="question-title-header"><%= @question.title %><h3>
  </div>
  <% if current_user %>
    <div class="question-vote-box">
      <%= form_tag({ controller: "votes", action: "update", vote_type: true, voteable: { id: @question, type: @question.class }}, method: "put", remote: true) do -%>
        <%= button_tag "Boss", :class => 'btn btn-success' %>
      <% end -%>
      <div class="question-score">
        <span><%= @question.vote_count %></span>
      </div>
      <%= form_tag({ controller: "votes", action: "update", vote_type: false, voteable: { id: @question, type: @question.class }}, method: "put", remote: true) do -%>
        <%= button_tag "Not Boss", :class => 'btn btn-danger' %>
      <% end %>
    </div>
  <% end %>

  <div class="question-body">
    <%= @question.body%>

  </div>
  <div class='clearfix'></div>
  <div class="question-info">
    <span class="user-name"><%= @question.user.username %></span> asked <%= time_ago_in_words(@question.created_at) %> ago

    <% if current_user %>
      <%= link_to 'comment on question', questions_path, :class => 'add-comment' %>
    <% else %>
      <p>You must be <%= link_to 'logged in', new_session_path %> to comment</p>
    <% end %>
  </div>
  <div class='comment-form-question'>
    <%= form_for [@question, @comment], remote: true, :html => {:class => 'question-comment-form' } do |t| %>
      <%= t.label :body, 'Comment' %>
      <%= t.text_field :body %>
      <%= t.button 'Submit Comment', :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<div class="question-comments col-md-12">
  <div class='display-comments'>
    <ul class='comment-list'>
      <% @question.comments.each do |comment| %>
        <%= render '/shared/comments', :comment => comment %>
      <% end %>
    </ul>
  </div>
</div>

<!-- <h4 class='col-md-12'>Answer this question:</h4> -->
<% if current_user %>
  <%= link_to 'Answer this Question', root_path, remote: true, :class => 'show-answer-form' %>
<% else %>
  <p>You must be <%= link_to 'logged in', new_session_path %> to answer</p>
<% end %>
<div id="answer-errors"></div>
<div class='answer-question col-md-8'>
  <%= form_for [@question, @answer], remote: true,:cols => "30", :rows => "1"  do |f| %>
    <div class="form-group">
      <%= f.label :body, 'answer' %>
      <%= f.text_area :body, :class => 'form-control' %>
      <%= f.button 'submit', :class => 'btn btn-primary' %>

    </div>
  <% end %>
</div>
<h2 class='col-md-12'>
    <span id='answer-count' data-count="<%= @question.answers.count %>"><%= @question.answers.count %></span> <%= pluralize_without_count(@question.answers.count, 'Answer',text = nil) %>
</h2>
<div class='answers col-md-8'>
  <ul class='answer-list'>
  <% @answers.each do |answer| %>
    <%= render '/shared/answers', :answer => answer %>
    <% if current_user %>
      <%= link_to 'Comment on this', root_path, remote: true, :class => 'show-comment-form', :data => {id: answer.id } %>
    <% else %>
      <p>You must be <%= link_to 'logged in', new_session_path %> to comment</p>
    <% end %>
    <div class='comment-form' id="answer<%= answer.id %>">
      <%= form_for [answer, @comment], remote: true, :html => {'data-id' => answer.id, :class => 'answer-comment-form' } do |t| %>
        <%= t.label :body, 'Comment Answer' %>
        <%= t.text_field :body %>
        <%= t.button 'Submit Answer Comment', :class => 'btn btn-primary' %>
      <% end %>
    </div>

  <div class='display-answer-comments'>
    <ul class='comment-list-answer' id="answer<%= answer.id %>" >
      <% answer.comments.each do |comment| %>
        <%= render '/shared/comments', :comment => comment %>
      <% end %>
    </ul>
  </div>

  <% end %>
</ul>
</div>

app/views/shared/_answers.html.erb
<li class='single-answer'>

  <div class="single-answer-body">
    <%= answer.body %>
  </div>
  <span class="single-answer-info"><span class='user-name'><%= answer.user.username %></span>  answered about <%= time_ago_in_words(answer.created_at) %> ago</span>
  <% if current_user %>
    <div class="answer-upvote-box">
      <%= form_tag({ controller: "votes", action: "update", vote_type: true, voteable: { id: answer.id, type: answer.class }}, method: "put", remote: true) do -%>
        <%= button_tag "Boss", :class => 'btn btn-success' %>
      <% end -%>
    </div>
      <div id="answer-score<%= answer.id %>">
        <span><%= answer.vote_count %></span>
      </div>
    <div class="answer-downvote-box">  
      <%= form_tag({ controller: "votes", action: "update", vote_type: false, voteable: { id: answer.id, type: answer.class }}, method: "put", remote: true) do -%>
        <%= button_tag "Not Boss", :class => 'btn btn-danger' %>
      <% end -%>
    </div>
  <% end %>
</li>

app/views/shared/_comments.html.erb
<li class='single-comment'>
  <div class="single-comment-body">
    <%= comment.body %>
  </div>
  <span class="single-comment-info"><span class='user-name'><%= comment.user.username %></span>  commented about <%= time_ago_in_words(comment.created_at) %> ago</span>
</li>

app/views/shared/_errors.html.erb
<p class="error"> <%= errors %></p>

app/views/shared/_header.html.erb
<div class="row header">
  <div class='col-md-4'>
    <h1><%= link_to 'Sports Overflow', root_path %></h1>
  </div>
  <div class='col-md-8'>
    <nav>
      <ul class="nav nav-pills">
        <li><%= link_to 'Home', root_path %></li>


        <% unless current_user %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Log In", new_session_path %></li>
        <% else %>
        <li><%= link_to 'Ask Question', new_question_path %>
        </li>
          <li><%= link_to "Log Out", session_path(current_user), method: :delete %></li>

        <% end %>
      </ul>
    </nav>
  </div>

</div>

app/views/shared/_recent.html.erb
<div id="recent">
    <ul class="homepage-questions">
      <% @questions.each do |question| %>
        <li>
          <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-4 single-question"><%= question.votes.count %></div>
             <div class="col-md-8 col-sm-8 col-xs-8 single-question">
              <%= link_to question.title, question_path(question) %>
              <span class="user-name"><%= question.user.username %></span> asked <%= time_ago_in_words(question.created_at) %> ago
             </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

app/views/shared/_trending.html.erb
<div id='trending'>
  <ul class="homepage-questions">
    <% @trending.each do |question, vote_time| %>
      <li>
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-4 single-question"><%= question.votes.count %></div>
           <div class="col-md-8 col-sm-8 col-xs-8 single-question">
            <%= link_to question.title, question_path(question) %>
            <span class="user-name"><%= question.user.username %></span> voted on <%= time_ago_in_words(vote_time) %> ago
           </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_vote_count.html.erb
<span><%= voteable.vote_count %></span>

app/views/shared/_votes.html.erb
<div id='votes'>
    <ul class="homepage-questions">
      <% @votes.each do |question, count| %>
        <li>
          <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-4 single-question"><%= question.votes.count %></div>
             <div class="col-md-8 col-sm-8 col-xs-8 single-question">
              <%= link_to question.title, question_path(question) %>
              <span class="user-name"><%= question.user.username %></span> asked <%= time_ago_in_words(question.created_at) %> ago
             </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, :placeholder => "Username" %><br>
  <%= f.label :email %>
  <%= f.text_field :email, :placeholder => "Email" %><br>
  <%= f.label :password %>
  <%= f.password_field :password, :placeholder => "Password" %><br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>

app/views/users/sign_up.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :email %>
  <%= f.text_field :email, :placeholder => "Email" %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.submit %>
<% end %>